### ISSUE TITLE
Listen macro not working as I assumed

### ISSUE THREAD

**Issue by Tranberry** [MalifaciousGames/Mali-s-Macros#1]
```xml
<<listen>>
    <h1>Passgae header</h1>
    <p>Press [Space] to play.</p>
    <div id="spacebar">
    </div>
    
    <style>
        #spacebar {
            ...
        }
    </style>
    
    <<when 'keypress'>>

    <<if _event.code === 'Space'>>
        <<goto "anotherPassage">>
    <</if>>

<</listen>>
```

I would assume that this would work, but instead of the `<<goto "anotherPassage">>` we tried anything from `<<run>>` to `<<script>>`. Please tell me if it is something silly I missed. 💛

**Comment by MalifaciousGames** [comment]
The issue is that `<<listen>>` only works for events that happen within its container, so the keypress happens on document level instead without ever bubbling through the container. 

This would work (tho it's not much of a solution):

```html
<<listen>>

    <<textbox '_whatever' ''>>
    
<<when 'keypress'>>

    <<if _event.code === 'Space'>>
        <<goto "anotherPassage">>
    <</if>>

<</listen>>
```

Chapel's event macro is more along the lines of what you're looking for, that said, my own `<<on>>` macro would work if it had a localised `_event` variable the same way `<<listen>>` does...

**Comment by MalifaciousGames** [comment]
This already works: 
```html
<<on 'keypress' '' onInit false>>
        <<goto "anotherPassage">>
<</on>>
```

Except you can't check for a keypress in particular...

**Comment by Tranberry** [comment]
> we weren't being idiots then

Thanks Mali for the great insight! 💛

**Comment by MalifaciousGames** [comment]
Quickest fix for now would be a simple:
```html
<<run $(document).one('keypress', (e) => {
    if (e.code === 'Space') { Engine.play('anotherPassage') };
})>>
```

**Comment by Tranberry** [comment]
yeah, but the plan was to write less js/jq. 👺

**Comment by MalifaciousGames** [comment]
Solved with the new `<<on>>` version, `readme` still needs to be written...
